#!/bin/bash

LANGUAGE=tfun
PROJECT_HOME=$(dirname "$0")/..
cd "$PROJECT_HOME" || exit 1

build_parser() {
    (
        echo "---| build parser"
        mkdir -p ./parser || exit 1

        deno run --allow-read --allow-write --allow-net --unsafely-ignore-certificate-errors \
            "https://raw.githubusercontent.com/littlelanguages/parspiler-cli/main/mod.ts" deno \
            --verbose \
            --scanner=./parser/Scanner.ts \
            --parser=./parser/Parser.ts \
            ../${LANGUAGE}/Grammar.llgd || exit 1

        echo "---| formatting built parser"
        deno fmt ./parser/*.ts || exit 1
    )
}

markdown_tests() {
    echo "---| markdown tests"

    deno run --allow-read ../test-runner/TestRunner.ts `find ../../scenarios -name "*.md"`
}

scenario_tests() {
    echo "---| scenario tests"

    for FILE in ../../scenarios/${LANGUAGE}/*.inp; do
	OUTPUT_FILENAME=../../scenarios/${LANGUAGE}/$(basename "$FILE" .inp).out 

        echo "- scenario test: $FILE"
        deno run --allow-read Repl.ts "$FILE" > t.txt || exit 1

        if ! diff -q "$OUTPUT_FILENAME" t.txt; then
            echo "scenario test failed: $FILE"
            diff "$OUTPUT_FILENAME" t.txt
            rm t.txt
            exit 1
        fi

        rm t.txt
    done
}

unit_tests() {
    echo "---| unit tests"

    deno test --allow-read || exit 1
}

case "$1" in
"" | help)
    echo "Usage: $0 [<command>]"
    echo "Commands:"
    echo "  help"
    echo "    This help page"
    echo "  markdown"
    echo "    Scenario tests stored in markdown files"
    echo "  parser"
    echo "    Builds the parser from specs"
    echo "  run"
    echo "    Run all tasks"
    echo "  run-watch"
    echo "    Run all tasks and watch for changes"
    echo "  scenario"
    echo "    Run all scenario tests"
    echo "  unit"
    echo "    Run all unit tests"
    ;;

run)
    build_parser
    unit_tests
    scenario_tests
    markdown_tests
    ;;

run-watch)
    ls -1 *.ts ../../scenarios/*.md | entr -c -s "$0 run"
    ;;

markdown)
    markdown_tests
    ;;

parser)
    build_parser
    ;;

scenario)
    scenario_tests
    ;;

unit)
    unit_tests
    ;;

*)
    echo "$0: $1: Unknown command"
    exit 1
    ;;
esac
